ALTER TABLE api_keys
    ADD COLUMN read_wallet BOOLEAN DEFAULT FALSE,
    ADD COLUMN create_invoice BOOLEAN DEFAULT FALSE,
    ADD COLUMN send_transaction BOOLEAN DEFAULT FALSE,
    ADD COLUMN edit_account BOOLEAN DEFAULT FALSE;