stages:
  # while we have a pretty simple CI setup, we run everything on one job
  - test

test:
  image: golangci/golangci-lint
  services:
    # If you're updating the postgres image we're using, make sure you've pushed
    # this to the registry. Otherwise the tests won't run with the newest image!
    - name: registry.gitlab.com/arcanecrypto/teslacoil/postgres
      # otherwise the host is name of the image
      alias: postgres
  only:
    - merge_requests
  stage: test
  # This is a hack, but that's because GitLab doesn't respect GOPATH etc
  # https://medium.com/@Extrawurst/golang-and-gitlab-ci-da97d11bafe1
  cache:
    paths:
      - .cache
  variables:
    DATABASE_HOST: postgres
  before_script:
    # cache things properly
    - mkdir -p $CI_PROJECT_DIR/.cache
    - export GOPATH="$CI_PROJECT_DIR/.cache"

    # make sure we're using Go modules
    - export GO111MODULE=on
  script:
    # run tests
    - make test_verbose

    # run linter
    - golangci-lint run
