#! /usr/bin/env bash

# If the -testnet flag hasn't been passed in, we add -regtest
if [[ $* != *-testnet* ]]; then
    NETWORK_FLAG="-regtest"
fi

docker exec --user bitcoin bitcoind bitcoin-cli $NETWORK_FLAG -rpcuser=$RPCUSER -rpcpassword=$RPCPASS $@
