#! /usr/bin/env bash
if [[ $* != *--network* ]]; then
    BITCOIN_NETWORK="regtest"
fi

exe() { echo "\$ $@" ; "$@" ; }


exe lncli --lnddir=docker/.bob --rpcserver=localhost:10010 --network $BITCOIN_NETWORK "$@"
