version: '2.2'
services:
  db:
    container_name: postgres
    command:
      - postgres
      - -c
      - logging_collector=on
      - -c
      - log_directory=/var/log/postgresql
      - -c
      - log_filename=postgres.log
      - -c
      - log_statement=all
    build:
      context: docker/postgres
    volumes:
      - postgres:/var/lib/postgresql
    environment:
      - DATABASE_USER
      - POSTGRES_PASSWORD
    ports:
      # expose default Postgres port as 5434 on host
      - 5434:5432
  bitcoind:
    # https://github.com/ruimarinho/docker-bitcoin-core
    image: ruimarinho/bitcoin-core:0.18
    container_name: bitcoind

    volumes:
      - bitcoin:/home/bitcoin/.bitcoin
    command:
      - -debug=rpc
      - -printtoconsole
      - -$BITCOIN_NETWORK
      - -rpcuser=$RPCUSER
      - -rpcpassword=$RPCPASS
      - -rpcbind=0.0.0.0
      - -rpcallowip=0.0.0.0/0
      - -txindex
      - -zmqpubrawtx=tcp://0.0.0.0:$ZMQPUBRAWTX_PORT
      - -zmqpubrawblock=tcp://0.0.0.0:$ZMQPUBRAWBLOCK_PORT

  lnd:
    build:
      context: docker/lnd
      args:
        # we want uid and gid to be the same as the current user
        # this is so permissions work out nicely when reading macaroon
        # files. By default Docker containers run as root, which
        # prevents us from reading the files we need
        uid: $uid
        gid: $gid
        LND_VERSION: '0.8.0-beta'
    environment:
      - RPCUSER
      - RPCPASS
      - BITCOIN_NETWORK
      - RPCHOST
      - DEBUG
      - ZMQPUBRAWTX_PORT
      - ZMQPUBRAWBLOCK_PORT
    command: sh -c './wait-for-bitcoind.sh && ./start-lnd.sh'

  bob:
    depends_on:
      - bitcoind
    extends: lnd
    container_name: bob
    environment:
      - RPCHOST=blockchain
    # expose Bob's LND RPC as a different than ALice's port
    ports:
      - '10010:10009'
    volumes:
      # Map ./.bob to Bobs LND data dir
      - ./docker/.bob:/home/lnd/.lnd
    links:
      - 'bitcoind:blockchain'

  alice:
    depends_on:
      - bitcoind
    extends: lnd
    container_name: alice
    environment:
      - RPCHOST=blockchain
    # expose Alice's LND RPC port
    ports:
      - '10009:10009'
    volumes:
      # Map ./.alice to Alice's LND data dir
      - ./docker/.alice:/home/lnd/.lnd
    links:
      - 'bitcoind:blockchain'

volumes:
  # bitcoin volume is needed for maintaining blockchain persistence
  # during bitcoind container recreation.
  bitcoin:

  # postgres volume is needed for persisting DB state
  # across container runs
  postgres:
